name: dumb_android
description: Flutter Client
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  record: ^6.1.2
  shared_preferences: ^2.2.2
  file_picker: 10.3.3
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  just_audio: ^0.9.35
  mime: ^1.0.4
  flutter_localizations:
    sdk: flutter
  web_socket_channel: ^3.0.0
  device_info_plus: ^9.0.0
  battery_plus: ^4.1.0
  cached_network_image: ^3.3.0
  dumb_api_dart: ^1.0.1
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_native_splash:
  color: "#42a5f5"
  color_dark: "#042a49"
 