name: dumb_android
description: Flutter Client
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  file_picker: ^10.2.0
  path_provider: ^2.1.1
  just_audio: ^0.9.35
  mime: ^1.0.4
  flutter_localizations:
    sdk: flutter
  web_socket_channel: ^2.4.0
  permission_handler: ^11.0.1
  record: ^6.1.2
  device_info_plus: ^10.0.0
  battery_plus: ^4.1.2
  system_info: ^2.0.3
  connectivity_plus: ^5.0.1
  package_info_plus: ^5.0.1
  sensors_plus: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
